#pragma once

#define UX_STANDALONE
#define UX_DEVICE_STANDALONE

#define UX_MAX_CLASS_DRIVER 1
#define UX_MAX_SLAVE_CLASS_DRIVER 1

#define UX_DEVICE_ENDPOINT_BUFFER_OWNER 1

#define UX_SLAVE_REQUEST_CONTROL_MAX_LENGTH 256
#define UX_SLAVE_REQUEST_DATA_MAX_LENGTH 512

#define UX_DEVICE_CLASS_CDC_ACM_READ_BUFFER_SIZE 64
#define UX_DEVICE_CLASS_CDC_ACM_WRITE_BUFFER_SIZE 64
