#ifndef RU_DRIVERS_STM32H5XX_EEPROM_EMUL_CONF_H
#define RU_DRIVERS_STM32H5XX_EEPROM_EMUL_CONF_H

#ifdef __cplusplus
extern "C" {
#endif

#define EE_ALGO_FLITF

#define EE_FLASH_BASE_ADDRESS FLASH_BASE
#define EE_START_PAGE_ADDRESS 0x081F6000UL
#define EE_FLASH_PAGE_SIZE FLASH_SECTOR_SIZE

#define EE_FRAME_LINE_SIZE 16UL

#define EE_CYCLES_NUMBER 1UL
#define EE_GUARD_PAGES_NUMBER 2UL
#define EE_NB_OF_VARIABLES 16UL

#ifdef __cplusplus
}
#endif

#endif
