#ifndef RU_DRIVERS_STM32H5XX_EEPROM_EMUL_CONF_H
#define RU_DRIVERS_STM32H5XX_EEPROM_EMUL_CONF_H

/* Project overrides are optional; defaults below keep the driver standalone. */
#if defined(__has_include)
#if __has_include("eeprom_mapping.h")
#include "eeprom_mapping.h"
#endif
#endif

#ifndef RU_STM32H5XX_EEPROM_FLASH_BASE_ADDRESS
#define RU_STM32H5XX_EEPROM_FLASH_BASE_ADDRESS FLASH_BASE
#endif

#ifndef RU_STM32H5XX_EEPROM_START_PAGE_ADDRESS
#define RU_STM32H5XX_EEPROM_START_PAGE_ADDRESS 0x081F8000UL
#endif

#ifndef RU_STM32H5XX_EEPROM_FLASH_PAGE_SIZE
#define RU_STM32H5XX_EEPROM_FLASH_PAGE_SIZE FLASH_SECTOR_SIZE
#endif

#ifndef RU_STM32H5XX_EEPROM_FRAME_LINE_SIZE
#define RU_STM32H5XX_EEPROM_FRAME_LINE_SIZE 16UL
#endif

#ifndef RU_STM32H5XX_EEPROM_CYCLES_NUMBER
#define RU_STM32H5XX_EEPROM_CYCLES_NUMBER 1UL
#endif

#ifndef RU_STM32H5XX_EEPROM_GUARD_PAGES_NUMBER
#define RU_STM32H5XX_EEPROM_GUARD_PAGES_NUMBER 2UL
#endif

#ifndef RU_STM32H5XX_EEPROM_NB_OF_VARIABLES
#define RU_STM32H5XX_EEPROM_NB_OF_VARIABLES 40UL
#endif

#ifndef RU_STM32H5XX_EEPROM_INIT_ERASE_TYPE
#define RU_STM32H5XX_EEPROM_INIT_ERASE_TYPE EE_CONDITIONAL_ERASE
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define EE_ALGO_FLITF

#define EE_FLASH_BASE_ADDRESS RU_STM32H5XX_EEPROM_FLASH_BASE_ADDRESS
#define EE_START_PAGE_ADDRESS RU_STM32H5XX_EEPROM_START_PAGE_ADDRESS
#define EE_FLASH_PAGE_SIZE RU_STM32H5XX_EEPROM_FLASH_PAGE_SIZE

#define EE_FRAME_LINE_SIZE RU_STM32H5XX_EEPROM_FRAME_LINE_SIZE

#define EE_CYCLES_NUMBER RU_STM32H5XX_EEPROM_CYCLES_NUMBER
#define EE_GUARD_PAGES_NUMBER RU_STM32H5XX_EEPROM_GUARD_PAGES_NUMBER
#define EE_NB_OF_VARIABLES RU_STM32H5XX_EEPROM_NB_OF_VARIABLES

#ifdef __cplusplus
}
#endif

#endif
