#pragma once

#include "stm32h5xx_hal.h"

#define RU_STM32H5XX_GPIO_MAP(X) \
  X(DEBUG_LED, GPIOE, GPIO_PIN_3, true, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_LOW)

#define RU_STM32H5XX_ADC_MAP(X) \
  X(ADC_0, ADC1, GPIOA, GPIO_PIN_1, ADC_CHANNEL_1) \
  X(ADC_1, ADC2, GPIOA, GPIO_PIN_2, ADC_CHANNEL_2)

#define RU_STM32H5XX_PWM_MAP(X) \
  X(PWM_0, TIM2, GPIOA, GPIO_PIN_3, TIM_CHANNEL_4, GPIO_AF1_TIM2)

#define RU_STM32H5XX_TIMER_MAP(X)

#define RU_STM32H5XX_SERIAL_MAP(X)

#define RU_STM32H5XX_M_CAN_MAP(X)

#define RU_STM32H5XX_BX_CAN_MAP(X) \
  X(CAN, FDCAN1)

#define RU_STM32H5XX_NV_MEMORY_MAP(X)

#define RU_STM32H5XX_WATCHDOG_MAP(X)
